export default {
    TooManyAttempt: 'Too many wrong attempts. Please try again later.',
    account: 'Account ',
    Favourite: 'Favourite ',
    signin: 'Sign in',
    menu: 'Menu',
    withcredentials: 'with your credentials',
    AccountLocked: 'Account Locked',
    LinkSend: "Link Send",
    ResetPassword: 'This link to reset your password has been sent on your email address',
    PasswordUpdated: 'Password Updated',
    PasswordUpdatedText: 'Your new password updated successfully',
    PasswordNotMatch: 'Passwords do not match. Please try again.',
    twoFA: 'To initiate the two-factor authentication, provide your phone number below.',
    addPhone: 'Add Phone Number',
    OTPverified: 'Your OTP has been verified successfully!',
    backtologin: "Back to login",
    success: 'Success',
    error: "Error",
    attemptsExhausted: "You have exhausted all attempts.",
    emailaddress: 'Email Address',
    ForgotPassword: 'Forgot Password',
    resetline: 'Reset your password in just a few clicks',
    emailnotfound: 'Email not found',
    emailempty: 'Email cannot be empty',
    invalidemailformat: 'Invalid email format',
    errortype: 'error',
    login: 'Login',
    forgotpasswordname: 'Forgot Password?',
    welcome: 'Welcome',
    kelvin: 'Kelvin',
    frequentlyused: 'FREQUENTLY USED',
    activities: 'ACTIVITIES',
    calender: 'Calender',
    customer: 'Customer',
    messages: 'Messages',
    linkaccount: "Link your account with your phone number",
    onetimepasscode: "Enter the one-time passcode",
    secureaccount: 'Secure your account',
    getstarted: 'Get Started',
    getstarted2fa: 'Setup Two factor authentication to secure your account in just two steps.',
    secureacc: 'Secure your Account?',
    messagetext: 'Hi @ankit, are you here?',
    prabhat: 'Prabhat mentioned you',
    time: '12:45',
    pt: 'PT',
    accountsetup: 'Complete your account setup',
    taptocontinue: 'Tap to continue',
    QUIVIO: 'QUIVIO',
    carwash: 'Your Personal CarWash Assistant',
    verifyac: 'Verify Account Access',
    entercode: 'Enter the code that we just sent to you on',
    number: '+1-788-895-5435',
    resend: 'Resend',
    exit:'Are you sure you want to exit 2FA,You will need to redo it again.',
    exit2fa:'Exit2FA',
    nocontinue:'No Continue',
    yesexit:'Yes exit',
    toomanyfailed:'Too Many Failed Attempts',
    editProfile:'Edit Profile',
    profilepic:'Profile Picture',
    changeprofile:'Change Photo',
    Update:'Update',
    male:'Male',
    female:'female',
    other:'other',
    gender:'Gender',
    usernameNeeded:'Username is required.',
    nameNeeded:'Name is required.',
    phoneNumberNeeded: "Phone number is required",
    dateNeeded: "Birthday is required",
    genderNeeded: "Gender is required",
    editProfile: "Edit Profile",
    profilepic: "Profile Picture",
    changeprofile: "Change Profile Picture",
    Update: "Update",
}